### ISSUE TITLE
Unable to open '/home/archerysec/app/nikto_result/...' for write

### ISSUE THREAD

**Issue by wheelq** [archerysec/archerysec#141]
**Issue**
When issuing a new domain scan using Nikto, app fails to run the scan

**To Reproduce**
1. Go to http://[hostname]:9000/webscanners/
2. Click on 'Scan->Domain'
3. Enter hostname and from the 'Scanners' list select 'Nikto' (has to be previously configured
4. Click 'Launch' button
5. run: ` docker logs archerysec `
6. See the error:

+ ERROR: Unable to open '/home/archerysec/app/nikto_result/d24ca828-2cfd-4102-562c-0814045231a1.html' for write:
1 at /var/lib/nikto/plugins/nikto_report_html.plugin line 47.
Internal Server Error: /tools/nikto/
Traceback (most recent call last):
  File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/archerysec/app/tools/views.py", line 163, in nikto
    nikto_scan_output=nikto_output)
NameError: global name 'nikto_output' is not defined
[03/Apr/2019 12:26:13] "POST /tools/nikto/ HTTP/1.1" 500 15500

**Desktop (please complete the following information):**
 - OS: RHEL7.5
 - Version latest docker, latest archerysec image, using docker-compose

**Comment by wheelq** [comment]
I ended up changing chmod and creating directories manually

**Comment by AndrijaGulan** [comment]
> I ended up changing chmod and creating directories manually

Sorry for bothering. Can you tell me what did you chmod and what dirs you created?

**Comment by wheelq** [comment]
mkdir -p /home/archerysec/app/nikto_result/
chmod -R 777 /home/archerysec/app
