### ISSUE TITLE
Facing issue with integration of ZAP in Docker

### ISSUE THREAD

**Issue by Nag0546** [archerysec/archerysec#26]
I am facing errors while connecting the ZAP . I am unable to connect and scan the domains or url's  and also i am trying to integrate within the same instance and as a separate instances. I am getting the following error while connecting with ZAP. And also it wont store any logs to check the results it shows everything as a empty files . Could you please help on this error.
Thanks in advance.

# [14/Jun/2018 17:05:40] "POST /webscanners/xml_upload/ HTTP/1.1" 302 0
[14/Jun/2018 17:05:40] "GET /webscanners/scans_list/ HTTP/1.1" 200 17271
[14/Jun/2018 17:06:45] "GET /webscanners/scans_list/ HTTP/1.1" 200 17271
split_lenght 1
[14/Jun/2018 17:06:51] "POST /webscanners/del_scan/ HTTP/1.1" 302 0
[14/Jun/2018 17:06:51] "POST /webscanners/zap_rescan/ HTTP/1.1" 302 0
Failed to parse: Zap Path:PORT
Failed to parse: Zap Path:PORT
Failed to parse: Zap Path:PORT
targets:----- www.google.com
Failed to parse: Zap Path:PORT
Failed to parse: Zap Path:PORT
Failed to parse: Zap Path:PORT
Spider Completed
[14/Jun/2018 17:06:52] "GET /webscanners/scans_list/ HTTP/1.1" 200 17560
[14/Jun/2018 17:06:53] "GET /webscanners/scans_list/ HTTP/1.1" 200 17564
Scanning Target www.google.com
Failed to parse: Zap Path:PORT
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField zap_scans_db.date_time received a naive datetime (2018-06-14 17:06:56.983405) while time zone support is active.
  RuntimeWarning)
Failed to parse: Zap Path:PORT
Exception in thread Thread-109:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/archerysec/webscanners/web_views.py", line 260, in launch_web_scan
    all_vuln = zap.zap_scan_result()
  File "/root/archerysec/scanners/scanner_plugin/web_scanner/zap_plugin.py", line 286, in zap_scan_result
    all_vuln = ZAPScanner.zap.core.alerts(self.target_url)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/core.py", line 49, in alerts
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'core/view/alerts/', params)))
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 159, in _request
    data = self._request_api(url, get)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 149, in _request_api
    return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 405, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 303, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 197, in proxy_manager_for
    **proxy_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 440, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 385, in __init__
    proxy = parse_url(proxy_url)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/url.py", line 199, in parse_url
    raise LocationParseError(url)
LocationParseError: Failed to parse: Zap Path:PORT

**Comment by anandtiwarics** [comment]
@Nag0546 are you using Docker ?

**Comment by Nag0546** [comment]
Yes @anandtiwarics 
I am using docker

**Comment by anandtiwarics** [comment]
@Nag0546 seems that issue with Docker and not able to connect with zap API endpoint. 

You can install in Kali for time being. Later we'll look at and solve this issue.

**Comment by frconetogit** [comment]
I'm in the same problem.

**Comment by anandtiwarics** [comment]
Hi @Nag0546 @Nag0546 @frconetogit ,

Fixed the issue. Please verify. 

Also, make sure that project should be created and settings form should be corrected. 
you can follow document to run [zap as Daemon mode](https://docs.archerysec.info/Scanners/zap-scanner/)

**Comment by cybernx** [comment]
roxyError: HTTPConnectionPool(host=u'127.0.0.1', port=8080): Max retries exceeded with url: http://zap/JSON/core/view/alerts/?apikey=&baseurl=https%3A%2F%2Fwww.xyz.com (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8881ada90>: Failed to establish a new connection: [Errno 111] Connection refused',)))

Getting this error that cant connect to http://zap/JSON/core/view/alerts?apikey
