### ISSUE TITLE
ZAP Settings - Zap_ports must be string and not int

### ISSUE THREAD

**Issue by Grounz** [archerysec/archerysec#321]
**Describe the bug**
When we define zap_proxy settings in api settings we get this error in archerysec container:

```
archerysec           | Traceback (most recent call last):
archerysec           |   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
archerysec           |     self.run()
archerysec           |   File "/usr/lib/python2.7/threading.py", line 754, in run
archerysec           |     self.__target(*self.__args, **self.__kwargs)
archerysec           |   File "/home/archerysec/app/webscanners/zapscanner/views.py", line 101, in launch_zap_scan
archerysec           |     zap_connect = zap_plugin.zap_connect()
archerysec           |   File "/home/archerysec/app/scanners/scanner_plugin/web_scanner/zap_plugin.py", line 90, in zap_connect
archerysec           |     'http': zap_hosts + ':' + zap_ports,
archerysec           | TypeError: coercing to Unicode: need string or buffer, int found
```

**To Reproduce**
1. Go to API
2. Click on ZAP_SETTING
3. Add Host 
4. Add Port
5. Watch log
6. See error

**Expected behavior**
Get and insert zap settings configuration

**Workaround**

Insert in scanners/scanner_plugin/web_scanner/zap_plugin.py this code above at line;

Because zap_ports var must be string and not int
```
    zap = ZAPv2(apikey=zap_api_key,
                proxies={
                    'http': zap_hosts + ':' + str(zap_ports),
                    'https': zap_hosts + ':' + str(zap_ports)})
```

**Comment by kraba** [comment]
> Insert in scanners/scanner_plugin/web_scanner/zap_plugin.py this code above at line;

Which code?

My zap connect is:

```
     67 def zap_connect():
     68     all_zap = zap_settings_db.objects.all()
     69
     70     zap_api_key = 'dwed23wdwedwwefw4rwrfw'
     71     zap_hosts = '127.0.0.1'
     72     zap_ports = '8090'
     73     zap_enabled = False
     74
     75     for zap in all_zap:
     76         zap_enabled = zap.enabled
     77
     78     if zap_enabled is False:
     79         zap_api_key = 'dwed23wdwedwwefw4rwrfw'
     80         zap_hosts = '127.0.0.1'
     81         zap_ports = '8090'
     82     elif zap_enabled is True:
     83         for zap in all_zap:
     84             zap_api_key = zap.zap_api
     85             zap_hosts = zap.zap_url
     86             zap_ports = zap.zap_port
     87
     88     zap = ZAPv2(apikey=zap_api_key,
     89                 proxies={
     90                     'http': zap_hosts + ':' + zap_ports,
     91                     'https': zap_hosts + ':' + zap_ports})
     92
```

and I have the same issue.

**Comment by Grounz** [comment]
I close this issue, because #321 fixe the bug.
