### ISSUE TITLE
Burpsuite Scan Result not available on Archerysec Burps Scan Dashboard after scan finish

### ISSUE THREAD

**Issue by ghost** [archerysec/archerysec#325]
Pelase help me..
I have a problem when scanning burpsuite on Archerysec, that is when I do scanning, there is no notification that it was done successfully or not and there are no reports that I get in the Archerysec dashboard.

I followed the tutorial below:
https://docs.archerysec.com/Scanners/burp-scanner/

**Comment by vijupawde** [comment]
Hello fligthautumn , i am facing same issue , scanning request is going to burp scanner but progress and results are not showing to archerysec dashboard , how did you solve this ? , please help me out

**Comment by Ntendo64** [comment]
Hi all,

Seems this issue was never solved. Here are some additional notes on the issue which I have observed.
The connection to burp works properly, under settings (i.e. Api Key, Host and Port are configured correctly and show up as working on Archerysec settings).

But when initiating a dynamic scan (type burp) - it doesn't result in anything, and when I took a closer look at the logs on the container I see the following error message:

`ERROR:django.request: Internal Server Error: /burpscanner/burp_launch_scan/ (2022-11-24 04:50:15; log.py:224)
Traceback (most recent call last):
  File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/archerysec/app/webscanners/burpscanner/views.py", line 213, in post
    ProjectDb.objects.filter(uu_id=project_uu_id).values("id").get()["id"]
  File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
projects.models.ProjectDb.DoesNotExist: ProjectDb matching query does not exist.`

So after digging around, I noticed that three files in particular are relevant to this error message:

./webscanners/burpscanner/views.py
./projects/models.py

To be more specific, under the views.py above, on lines 212-214 we see the following code:
`        project_id = (
            ProjectDb.objects.filter(uu_id=project_uu_id).values("id").get()["id"]
        )`

That is the code which seems to be causing the error messages

please can we reopen this issue and investiage as it is not solved yet.

**Comment by anandtiwarics** [comment]
hi, @Ntendo64 The issue has been fixed now. let me know if its still not working
