### ISSUE TITLE
[Docker] Permission denied

### ISSUE THREAD

**Issue by SecT0uch** [archerysec/archerysec#333]
**Describe the bug**
I tried on both, last commit and last tag (1.2).
During the the launch of docker (with docker-compose), I get a permission denied error : 
```
archerysec-worker    | Copying '/home/archerysec/app/archerysecurity/static/archery.png'
archerysec-worker    | Traceback (most recent call last):
archerysec-worker    |   File "manage.py", line 25, in <module>
archerysec-worker    |     execute_from_command_line(sys.argv)
archerysec-worker    |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
archerysec-worker    |     utility.execute()
archerysec-worker    |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
archerysec-worker    |     self.fetch_command(subcommand).run_from_argv(self.argv)
archerysec-worker    |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
archerysec-worker    |     self.execute(*args, **cmd_options)
archerysec-worker    |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
archerysec-worker    |     output = self.handle(*args, **options)
archerysec-worker    |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
archerysec-worker    |     collected = self.collect()
archerysec-worker    |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
archerysec-worker    |     handler(path, prefixed_path, storage)
archerysec-worker    |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 364, in copy_file
archerysec-worker    |     self.storage.save(prefixed_path, source_file)
archerysec-worker    |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/files/storage.py", line 54, in save
archerysec-worker    |     return self._save(name, content)
archerysec-worker    |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/files/storage.py", line 321, in _save
archerysec-worker    |     os.makedirs(directory)
archerysec-worker    |   File "/usr/lib/python2.7/os.py", line 157, in makedirs
archerysec           | Traceback (most recent call last):
archerysec           |   File "manage.py", line 25, in <module>
archerysec           |     execute_from_command_line(sys.argv)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
archerysec           |     utility.execute()
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
archerysec           |     self.fetch_command(subcommand).run_from_argv(self.argv)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
archerysec           |     self.execute(*args, **cmd_options)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
archerysec           |     output = self.handle(*args, **options)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
archerysec           |     collected = self.collect()
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
archerysec           |     handler(path, prefixed_path, storage)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 364, in copy_file
archerysec           |     self.storage.save(prefixed_path, source_file)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/files/storage.py", line 54, in save
archerysec           |     return self._save(name, content)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/files/storage.py", line 321, in _save
archerysec           |     os.makedirs(directory)
archerysec           |   File "/usr/lib/python2.7/os.py", line 157, in makedirs
archerysec           |     mkdir(name, mode)
archerysec           | OSError: [Errno 13] Permission denied: '/home/archerysec/app/static'
archerysec-worker    |     mkdir(name, mode)
archerysec-worker    | OSError: [Errno 13] Permission denied: '/home/archerysec/app/static'
```

**To Reproduce**
1. Clone the repo
2. `cd archerysec`
3. `sudo docker-compose up`

**Expected behavior**
No error message.

**Desktop (please complete the following information):**
 - OS: Centos Stream (same as 8)

**Comment by CyberAbwehr** [comment]
The issue is that there is now directory /home/archerysec/app/static

Open a shell and try following commands
mkdir /home/archerysec/app/static
chown Archerysec /home/archerysec/app/static
chgrp archerysec /home/archerysec/app/static

After that I have got no permission error.
