### ISSUE TITLE
[Docker] NoReverseMatch error

### ISSUE THREAD

**Issue by SecT0uch** [archerysec/archerysec#335]
**Describe the bug**
Using master branch.
While using (with docker-compose), I get a NoReverseMatch error : 
```
archerysec           | [28/Nov/2019 09:10:20] "GET /static/matrix-admin-bt4/dist/css/icons/themify-icons/themify-icons.css HTTP/1.1" 200 8192
archerysec           | [2019-11-28 09:10:20,024] - Broken pipe from ('10.43.0.84', 57300)
archerysec           | 
archerysec           | [28/Nov/2019 09:10:20] "GET /static/matrix-admin-bt4/dist/css/icons/material-design-iconic-font/css/materialdesignicons.min.css HTTP/1.1" 200 77561
archerysec           | Internal Server Error: /api/docs/
archerysec           | Traceback (most recent call last):
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
archerysec           |     response = get_response(request)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
archerysec           |     response = self.process_exception_by_middleware(e, request)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
archerysec           |     response = response.render()
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
archerysec           |     self.content = self.rendered_content
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/rest_framework/response.py", line 72, in rendered_content
archerysec           |     ret = renderer.render(self.data, accepted_media_type, context)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/rest_framework/renderers.py", line 878, in render
archerysec           |     return template.render(context, request=renderer_context['request'])
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
archerysec           |     return self.template.render(context)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
archerysec           |     return self._render(context)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/test/utils.py", line 107, in instrumented_test_render
archerysec           |     return self.nodelist.render(context)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
archerysec           |     bit = node.render_annotated(context)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
archerysec           |     return self.render(context)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
archerysec           |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
archerysec           |   File "/home/archerysec/.local/lib/python2.7/site-packages/django/urls/base.py", line 87, in reverse
archerysec           |     raise NoReverseMatch("%s is not a registered namespace" % key)
archerysec           | NoReverseMatch: u'api-docs' is not a registered namespace
archerysec           | [28/Nov/2019 09:10:29] "GET /api/docs/ HTTP/1.1" 500 159708
archerysec           | Not Found: /favicon.ico
archerysec           | [28/Nov/2019 09:10:30] "GET /favicon.ico HTTP/1.1" 404 7080
```

**To Reproduce**
1. Clone the repo
2. `cd archerysec`
3. `sudo docker-compose up`
4. Use archery.

**Expected behavior**
No error message.

**Desktop (please complete the following information):**
 - OS: Centos Stream (same as 8)

**Comment by SecT0uch** [comment]
I don't know how to reproduce so I closed the issue.
