### ISSUE TITLE
Docker-compose: ImportError: cannot import name 'Feature'

### ISSUE THREAD

**Issue by d3skdev** [archerysec/archerysec#349]
**Describe the bug**
I'm encountering an error after running docker-compose command 

**To Reproduce**
- docker-compose up

**Expected behavior**
All containers should be up and running

**OS:**
- mac os, kali linux

**Error Logs**
```
...
Collecting lxml==4.3.3
Downloading lxml-4.3.3-cp36-cp36m-manylinux1_x86_64.whl (5.7 MB)
Collecting MarkupSafe==1.0
Downloading MarkupSafe-1.0.tar.gz (14 kB)
ERROR: Command errored out with exit status 1:
command: /home/archerysec/app/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2ufa4ooj/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2ufa4ooj/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-2ufa4ooj/MarkupSafe/pip-egg-infocwd: /tmp/pip-install-2ufa4ooj/MarkupSafe/
Complete output (5 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-2ufa4ooj/MarkupSafe/setup.py", line 6, in <module>
from setuptools import setup, Extension, Feature
ImportError: cannot import name 'Feature'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'archerysec' failed to build: The command '/bin/sh -c . venv/bin/activate && pip3 install --no-cache-dir -r requirements_setup.txt &&     rm -rf /home/archerysec/.cache' returned a non-zero code: 1
```

**Complete logs**
[https://pastebin.com/2mCu9Crx](https://pastebin.com/2mCu9Crx)

**Comment by MeepoPeepo** [comment]
i meet this error, too

**Comment by anandtiwarics** [comment]
the issue fixed, please check now.
