### ISSUE TITLE
crash after nmap scan

### ISSUE THREAD

**Issue by telekomancer** [archerysec/archerysec#366]
**When i run the nmap against docker host the dashboard crash**
If you scan your own docker machine, the dashboard crash

**To Reproduce**
1. Go to 'Launch Scans'
2. Click on 'Infrastructure scan'
![imagen](https://user-images.githubusercontent.com/27900350/84091191-b8a7ac00-a9c1-11ea-8bf0-546cc83b1f75.png)
3. Wait until the scan finish
3a. You can see via CLI when the scan finish
3b. Attach CLI log:
```
[NMAP_VULNERS][a0738afa-537f-48e0-baa1-e9a4a2358e9e] - ARGUMENTS - -sV -T5 --script /home/archerysec/app/archerysecurity/../tools/nmap_vulners/vulners.nse
Not Found: /nmaplowercheck1591659727
Not Found: /sdk
Not Found: /HNAP1
[NMAP_VULNERS][a0738afa-537f-48e0-baa1-e9a4a2358e9e] ----------------------------------------------------
[NMAP_VULNERS][a0738afa-537f-48e0-baa1-e9a4a2358e9e] Host : 172.16.162.139 ([{'name': '', 'type': ''}])
[NMAP_VULNERS][a0738afa-537f-48e0-baa1-e9a4a2358e9e] Host : 172.16.162.139, proto tcp, ports ({22: {'state': 'open', 'reason': 'syn-ack', 'name': 'ssh', 'product': 'OpenSSH', 'version': '7.4', 'extrainfo': 'protocol 2.0', 'conf': '10', 'cpe': 'cpe:/a:openbsd:openssh:7.4'}, 8000: {'state': 'open', 'reason': 'syn-ack', 'name': 'http', 'product': 'Gunicorn', 'version': '19.9.0', 'extrainfo': '', 'conf': '10', 'cpe': 'cpe:/a:gunicorn:gunicorn:19.9.0', 'script': {'http-server-header': 'gunicorn/19.9.0'}}})
```

```
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/archerysec/app/dashboard/views.py", line 102, in dashboard
    'message': all_notify
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 173, in render
    len_values = len(values)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/query.py", line 62, in __iter__
    for row in compiler.results_iter(results):
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 847, in results_iter
    row = self.apply_converters(row, converters)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 832, in apply_converters
    value = converter(value, expression, self.connection, self.query.context)
TypeError: from_db_value() takes 4 positional arguments but 5 were given
Not Found: /favicon.ico
```

**Expected behavior**
The scan should be somewhere at the dashboard 

**Server info:**
 - OS: 
```
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```
nmap --version

Nmap version 6.40 ( http://nmap.org )
Platform: x86_64-redhat-linux-gnu
Compiled with: nmap-liblua-5.2.2 openssl-1.0.2k libpcre-8.32 libpcap-1.5.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

```
docker --version
Docker version 19.03.11, build 42e35e61f3
```

**Additional context**
The system was installed with the following params
```
mkdir /home/tools
cd /home/tools
git clone https://github.com/archerysec/archerysec.git
cd archerysec/
cp archerysecurity/local_settings.sample.py archerysecurity/local_settings.py
pip3.6 install --upgrade pip
pip3.6 install virtualenv
pip3.6 install Django==2.1.*
pip3.6 install -r requirements.txt
python3.6 manage.py collectstatic
python3.6 manage.py migrate
python3.6 manage.py initadmin

#nmap vulners

cd /usr/share/nmap/scripts/
sudo wget https://raw.githubusercontent.com/vulnersCom/nmap-vulners/master/vulners.nse -O /usr/share/nmap/scripts/vulners.nse
cd

#docker

docker pull archerysec/archerysec
docker run -it -p 8000:8000 archerysec/archerysec:latest
```

By now, _archerysec_ is unusable due the problem with dashboard

![imagen](https://user-images.githubusercontent.com/27900350/84091191-b8a7ac00-a9c1-11ea-8bf0-546cc83b1f75.png)

![imagen](https://user-images.githubusercontent.com/27900350/84091508-919daa00-a9c2-11ea-82ee-ef9887a4ea6f.png)

**Traceback info**
```
Environment:


Request Method: GET
Request URL: http://172.16.162.139:8000/

Django Version: 1.11.29
Python Version: 3.6.9
Installed Applications:
['archerysecurity',
 'rest_framework',
 'webscanners',
 'projects',
 'archerysettings',
 'networkscanners',
 'staticscanners',
 'jiraticketing',
 'tools',
 'manual_scan',
 'django.contrib.admin',
 'stronghold',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework.authtoken',
 'debug_toolbar',
 'easy_pdf',
 'dashboard',
 'background_task',
 'sitetree',
 'import_export',
 'vFeedgui',
 'compliance',
 'notifications']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'stronghold.middleware.LoginRequiredMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware']


Template error:
In template /home/archerysec/app/webscanners/templates/notification.html, error at line 87
   from_db_value() takes 4 positional arguments but 5 were given   77 :                                                     aria-haspopup="true" aria-expanded="false"
   78 :                                                     class="nav-link dropdown-toggle waves-effect waves-dark">
   79 :     <i class="mdi mdi-bell font-24"></i><span
   80 :         class="notify-badge badge-pill badge-danger">{% load notifications_tags %}{% live_notify_badge %}</span> <span
   81 :         class="text"></span> <b class="caret"></b></a>
   82 :     <ul class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown" aria-labelledby="2">
   83 :         <ul class="list-style-none" style="margin:20px;width:410px">
   84 :             <li role="presentation">
   85 :             <a href="{% url 'webscanners:del_all_notify' %}" class="dropdown-menu-header">Clear All</a>
   86 :         </li>
   87 :              {% for data in message %} 
   88 :             <li>
   89 :                 <div class="alert alert-info alert-block">
   90 :                     <a class="close" data-dismiss="alert" href="/webscanners/del_notify?notify_id={{data.id}}"><i class="mdi mdi-close"></i></a>
   91 :                     <br>
   92 :                     {{data.verb}}
   93 :                     <!--<a href="/webscanners/del_notify?notify_id={{data.id}}"> <i class="mdi mdi-close"></i></a>-->
   94 :                 </div>
   95 :             </li>
   96 :             {% endfor %}
   97 :         </ul>


Traceback:

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/archerysec/app/dashboard/views.py" in dashboard
  102.                    'message': all_notify

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/shortcuts.py" in render
  30.     content = loader.render_to_string(template_name, context, request, using=using)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader.py" in render_to_string
  68.     return template.render(context, request)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/backends/django.py" in render
  66.             return self.template.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render
  207.                     return self._render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py" in instrumented_test_render
  107.     return self.nodelist.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py" in instrumented_test_render
  107.     return self.nodelist.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py" in instrumented_test_render
  107.     return self.nodelist.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  216.                 return template.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render
  209.                 return self._render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py" in instrumented_test_render
  107.     return self.nodelist.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/loader_tags.py" in render
  216.                 return template.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render
  209.                 return self._render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/test/utils.py" in instrumented_test_render
  107.     return self.nodelist.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/template/defaulttags.py" in render
  173.             len_values = len(values)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/query.py" in __len__
  232.         self._fetch_all()

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/query.py" in _fetch_all
  1121.             self._result_cache = list(self._iterable_class(self))

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/query.py" in __iter__
  62.         for row in compiler.results_iter(results):

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py" in results_iter
  847.                     row = self.apply_converters(row, converters)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py" in apply_converters
  832.                 value = converter(value, expression, self.connection, self.query.context)

Exception Type: TypeError at /
Exception Value: from_db_value() takes 4 positional arguments but 5 were given
```

**Comment by telekomancer** [comment]
Am not a developer neither a python expert, but i think that it's related to [!this change](https://github.com/archerysec/archerysec/commit/f1adfd5ee6278bab6f9894f9527d6c0fc981b5dd)

**Comment by anandtiwarics** [comment]
hey, thanks for reporting to us. I'm looking into this issue, will update you soon.

**Comment by anandtiwarics** [comment]
From my initial investigation, I found that the issue with the notification signal. 

You need to clean notification by accessing this URL [http://localhost:8000/webscanners/del_all_notify](http://localhost:8000/webscanners/del_all_notify) 

I'll fix it soon and release the new version.

**Comment by telekomancer** [comment]
Hi @anandtiwarics it's fixed ? let me know to test ;-)

Kind regards!

**Comment by anandtiwarics** [comment]
@telekomancer yes, it is fixed. Please test from your end and let me know.

**Comment by telekomancer** [comment]
Perfect, works.

Now, i have a question, i don't know if you prefer that i create a new issue or what but the scan finished, it's reflected at tools->NMAP->IP. 

But **NOT** in Project List->ProjectName->Infrastructure Scan List.

I guess that it's because that graph show's vulnerabilities and scoring, and an nmap scan doesn't show that ... a vulnerability and scoring (L-M-H).

Regardless of this and if my _logic_ it's right, this issue should be closed and nmap scan without vuln. scoring shouldn't appear at Infrastructure Scan List.

I'll test the entire software and i'll tell you if i found another issues ;-)

Kind regards and thx for your support and replies @anandtiwarics

**Comment by telekomancer** [comment]
@anandtiwarics #367 it's partially related to this but only a half, not completely so please, reopen, _arachni connection issues_ persist

**Comment by anandtiwarics** [comment]
@telekomancer I'll check and let you know. Thanks.
