### ISSUE TITLE
Can up Archerysec in my Docker

### ISSUE THREAD

**Issue by lyoko17220** [archerysec/archerysec#37]
**Describe the bug**
Python makes a error when I want to up Archery. We can't have access to web plateform too

**To Reproduce**

```
nsagot@wall-e:~/.ssh$ docker run -it -p 8000:8000 archerysec/archerysec:latest
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f4617de3578>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/archerysec/archerysecurity/urls.py", line 25, in <module>
    url(r'^networkscanners/', include('networkscanners.urls')),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/archerysec/networkscanners/urls.py", line 13, in <module>
    from networkscanners import views
  File "/root/archerysec/networkscanners/views.py", line 34, in <module>
    from scanners.scanner_plugin.network_scanner.openvas_plugin import OpenVAS_Plugin, vuln_an_id
  File "/root/archerysec/scanners/scanner_plugin/network_scanner/openvas_plugin.py", line 1, in <module>
    from openvas_lib import VulnscanManager, VulnscanException
ImportError: No module named openvas_lib
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Docker version : 18.05.0-ce

**Comment by anandtiwarics** [comment]
Aaah ... got the issue. Let me fix this.

openvas_lib was recently updated and the package was broken.

**Comment by anandtiwarics** [comment]
@lyoko17220 

Just fixed the issue. Please try now, should be work fine.
