### ISSUE TITLE
Getting integrity error after doing zap and burp scan

### ISSUE THREAD

**Issue by sinnik** [archerysec/archerysec#397]
-- linux machine postgre db installation done throught setup.sh

Request Method: | GET
-- | --
http://capldot05:8000/dashboard/
3.1.2
IntegrityError
null value in column "high" violates not-null constraint DETAIL:  Failing row contains (3, 10, null, null, null, devsecopsuser-desl, f7f95e5b-be7a-4fd7-9f78-295b3d0e35c5).
/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/backends/utils.py, line 84, in _execute
/appl/cicd/products/devsecops/archerysec/venv/bin/python3
3.8.0
['/appl/cicd/products/devsecops/archerysec',  '/appl/cicd/products/devsecops/archerysec/venv/bin',  '/opt/rh/rh-python38/root/usr/lib64/python38.zip',  '/opt/rh/rh-python38/root/usr/lib64/python3.8',  '/opt/rh/rh-python38/root/usr/lib64/python3.8/lib-dynload',  '/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages',  '/appl/cicd/products/devsecops/archerysec/venv/lib/python3.8/site-packages',  '/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/odf',  '/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/odf',  '/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/odf',  '/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/odf',  '/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/odf',  '/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/odf',  '/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/odf']
Wed, 14 Oct 2020 12:32:04 +0000

Environment:

Request Method: GET
Request URL: http://capldot05:8000/dashboard/

Django Version: 3.1.2
Python Version: 3.8.0
Installed Applications:
['archerysecurity',
 'rest_framework',
 'webscanners',
 'projects',
 'archerysettings',
 'networkscanners',
 'staticscanners',
 'jiraticketing',
 'tools',
 'manual_scan',
 'django.contrib.admin',
 'stronghold',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework.authtoken',
 'debug_toolbar',
 'dashboard',
 'background_task',
 'sitetree',
 'import_export',
 'compliance',
 'notifications']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'stronghold.middleware.LoginRequiredMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware']

Traceback (most recent call last):
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (null value in column "high" violates not-null constraint
DETAIL:  Failing row contains (3, 10, null, null, null, devsecopsuser-desl, f7f95e5b-be7a-4fd7-9f78-295b3d0e35c5).
) was the direct cause of the following exception:
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/appl/cicd/products/devsecops/archerysec/dashboard/views.py", line 155, in dashboard
    month_db.objects.filter(username=username, project_id=proj_id, month=current_month).update(high=high,
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/models/query.py", line 784, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1522, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/appl/cicd/products/devsecops/archerysec/venv/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /dashboard/
Exception Value: null value in column "high" violates not-null constraint
DETAIL:  Failing row contains (3, 10, null, null, null, devsecopsuser-desl, f7f95e5b-be7a-4fd7-9f78-295b3d0e35c5).

**Comment by anandtiwarics** [comment]
can you pull the latest code and try to run the scan again? recently got fixed this issue.

**Comment by sinnik** [comment]
Using the latest commit from master still facing this issue after running the burp an zap scan.

**Comment by anandtiwarics** [comment]
seems it's conflicting with database entry... can you please try to create a fresh new database and run setup.sh and run.sh script... 

try [Vagrant Ansible](https://github.com/archerysec/archerysec-vagrant-ansible ) script if you still getting error
