### ISSUE TITLE
TypeError running migration on initial Kali box install

### ISSUE THREAD

**Issue by RVN-BR** [archerysec/archerysec#4]
I am trying to get this up in a kali box, however when running migration this is coming back and if I try to start the server it just gives an app error...

```
`# python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, networkscanners, projects, sessions, webscanners
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying networkscanners.0001_initial... OK
  Applying networkscanners.0002_auto_20180221_2122... OK
  Applying projects.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying webscanners.0001_initial... OK
  Applying webscanners.0002_auto_20180221_2123...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 88, in database_forwards
    field,
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/schema.py", line 238, in add_field
    self._remake_table(model, create_field=field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/schema.py", line 113, in _remake_table
    self.effective_default(create_field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 229, in effective_default
    default = field.get_db_prep_save(default, self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 770, in get_db_prep_save
    prepared=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 2387, in get_db_prep_value
    value = self.to_python(value)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 2396, in to_python
    return uuid.UUID(value)
  File "/usr/lib/python2.7/uuid.py", line 133, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
TypeError: an integer is required
`
```

Any ideas?

PS: have you guys thought of making a docker image available for easy testing and deploy?

**Comment by anandtiwarics** [comment]
Hi, 

Thank you for issue report. I have fixed this issue and push the updated code. Plese clone again and follow these commend:

```
$ git clone https://github.com/archerysec/archerysec.git
$ cd archerysec
$ pip install -r requirements.txt
$ python manage.py collectstatic
$ python manage.py makemigrations networkscanners
$ python manage.py makemigrations webscanners
$ python manage.py makemigrations projects
$ python manage.py makemigrations APIScan
$ python manage.py migrate
$ python manage.py createsuperuser
$ python manage.py runserver
```

Hope this will work for you.

We are planning to have docker image in future. Thanks.

**Comment by RVN-BR** [comment]
Thanks @anandtiwarics !

It seems to be working.  I'm putting together a docker file for my testing, and will share it with you.  One problem I've stumbled on is creating the superuser is an interactive command, which docker doesnt like for obvious reasons.  Is there any way to create the user by adding a file or using the createuser command with all arguments in the CLI?

I'm going over the code but since I am not at all familiar with python or django I havent been able to trace from the manage.py to where it creates the user.  I'm still looking but if there is any other way to do it from the CLI in one command, please point it out to me.  As soon as its working I'll post the dockerfile here in case you want to share it.

**Comment by anandtiwarics** [comment]
Great! I got your point. I'll work on signup page or create account page which will help the user to create the account without using the command in CLI. I'll update you once signup page ready.

Thanks for your inputs. :)

**Comment by anandtiwarics** [comment]
Sign up functionality pushed on Github. Please check now.
