### ISSUE TITLE
Django server errors

### ISSUE THREAD

**Issue by elmikel1** [archerysec/archerysec#49]
When I try to merge OWASP Zap, in Archery console I saw an error like bellow. Also
I receive similar one when I try options: 'covert to pdf' and 'add a cookie' in scanning option.

My OS: Kali Linux 2018

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 115, in process_response
    if response.status_code == 404:
AttributeError: 'unicode' object has no attribute 'status_code'
[10/Jul/2018 18:28:17] "POST /webscanners/scan_launch HTTP/1.1" 500 16794
```

**Comment by anandtiwarics** [comment]
Seems that ZAP API's are not working. Can you please check by accessing ZAP API manually and let us know if it's not working.

**Comment by anandtiwarics** [comment]
I'm closing the ticket. Let me know if you have still issue.
