### ISSUE TITLE
Exception when uploading Nessus scan

### ISSUE THREAD

**Issue by freqnoiz** [archerysec/archerysec#490]
After exporting the scan from Nessus as **.nessus** file, I am trying to upload it via Scans -> Infrastructure Scans -> Upload (Nessus).

After a while I get:

```Traceback (most recent call last):
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/archerysec/networkscanners/views.py", line 519, in xml_upload
    return HttpResponseRedirect(reverse("nessus:nessus_list"))
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'nessus' is not a registered namespace
ERROR:django.request: Internal Server Error: /networkscanners/xml_upload/ (2021-08-22 12:53:11; log.py:224)
Traceback (most recent call last):
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'nessus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/archerysec/networkscanners/views.py", line 519, in xml_upload
    return HttpResponseRedirect(reverse("nessus:nessus_list"))
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'nessus' is not a registered namespace

Environment:

Request Method: POST
Request URL: http://10.0.0.79:8000/networkscanners/xml_upload/

Django Version: 3.1.12
Python Version: 3.9.2
Installed Applications:
['archerysecurity',
 'rest_framework',
 'webscanners',
 'projects',
 'archerysettings',
 'networkscanners',
 'staticscanners',
 'jiraticketing',
 'tools',
 'manual_scan',
 'django.contrib.admin',
 'stronghold',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework.authtoken',
 'debug_toolbar',
 'dashboard',
 'background_task',
 'sitetree',
 'import_export',
 'compliance',
 'notifications',
 'rest_framework_jwt']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'stronghold.middleware.LoginRequiredMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware']



Traceback (most recent call last):
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]

During handling of the above exception ('nessus'), another exception occurred:
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/archerysec/networkscanners/views.py", line 519, in xml_upload
    return HttpResponseRedirect(reverse("nessus:nessus_list"))
  File "/root/archerysec/venv/lib64/python3.9/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)

Exception Type: NoReverseMatch at /networkscanners/xml_upload/
Exception Value: 'nessus' is not a registered namespace
```

However, it seems like some ( maybe all ) vulns get populated.

**Comment by Keldorb** [comment]
I have the same problem, my nessus file is about 36MB big. 
I use the docker container because python 2.x in kali is fucked up. In case i could send more error reports.
Here my log

Console:
```
Internal Server Error: /networkscanners/xml_upload/
Traceback (most recent call last):
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'nessus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/archerysec/app/networkscanners/views.py", line 519, in xml_upload
    return HttpResponseRedirect(reverse("nessus:nessus_list"))
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'nessus' is not a registered namespace
ERROR:django.request: Internal Server Error: /networkscanners/xml_upload/ (2021-09-03 13:12:08; log.py:230)
Traceback (most recent call last):
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'nessus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/archerysec/app/networkscanners/views.py", line 519, in xml_upload
    return HttpResponseRedirect(reverse("nessus:nessus_list"))
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'nessus' is not a registered namespace
```

Environment:
```
Request Method: POST
Request URL: http://0.0.0.0:8000/networkscanners/xml_upload/

Django Version: 3.1.12
Python Version: 3.6.9
Installed Applications:
['archerysecurity',
 'rest_framework',
 'webscanners',
 'projects',
 'archerysettings',
 'networkscanners',
 'staticscanners',
 'jiraticketing',
 'tools',
 'manual_scan',
 'django.contrib.admin',
 'stronghold',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework.authtoken',
 'debug_toolbar',
 'dashboard',
 'background_task',
 'sitetree',
 'import_export',
 'compliance',
 'notifications',
 'rest_framework_jwt']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'stronghold.middleware.LoginRequiredMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware']



Traceback (most recent call last):
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]

During handling of the above exception ('nessus'), another exception occurred:
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/archerysec/app/networkscanners/views.py", line 519, in xml_upload
    return HttpResponseRedirect(reverse("nessus:nessus_list"))
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)

Exception Type: NoReverseMatch at /networkscanners/xml_upload/
Exception Value: 'nessus' is not a registered namespace

```

**Comment by anandtiwarics** [comment]
this issue should be fixed. please try to use an already released version of archerysec instead directly from master branch.
