### ISSUE TITLE
Could not upload trivy report

### ISSUE THREAD

**Issue by Premfer** [archerysec/archerysec#509]
Hi Team,

when trying to upload the trivy json to the archery sec, we are getting this error. Can you please help with this.  In UI also file not supported error is [thrown.](url)

```
Traceback (most recent call last):
2021-10-04T08:38:22.4273006Z   File "/usr/local/bin/archerysec-cli", line 8, in <module>
2021-10-04T08:38:22.4274049Z     sys.exit(main())
2021-10-04T08:38:22.4276515Z   File "/home/zuser/.local/lib/python3.9/site-packages/archerysec_cli/cli/cli.py", line 460, in main
2021-10-04T08:38:22.4278048Z     scan_action()
2021-10-04T08:38:22.4279094Z   File "/home/zuser/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
2021-10-04T08:38:22.4279952Z     return self.main(*args, **kwargs)
2021-10-04T08:38:22.4281372Z   File "/home/zuser/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
2021-10-04T08:38:22.4282150Z     rv = self.invoke(ctx)
2021-10-04T08:38:22.4284725Z   File "/home/zuser/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
2021-10-04T08:38:22.4287165Z     return ctx.invoke(self.callback, **ctx.params)
2021-10-04T08:38:22.4288857Z   File "/home/zuser/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
2021-10-04T08:38:22.4289741Z     return callback(*args, **kwargs)
2021-10-04T08:38:22.4290761Z   File "/home/zuser/.local/lib/python3.9/site-packages/archerysec_cli/cli/cli.py", line 102, in scan_action
2021-10-04T08:38:22.4291421Z     upload_report(
2021-10-04T08:38:22.4292393Z   File "/home/zuser/.local/lib/python3.9/site-packages/archerysec_cli/cli/cli.py", line 245, in upload_report
2021-10-04T08:38:22.4293116Z     scan_data = archerysec.json_upload(file=report_path)
2021-10-04T08:38:22.4294492Z   File "/home/zuser/.local/lib/python3.9/site-packages/archerysec_cli/util/api.py", line 65, in json_upload
2021-10-04T08:38:22.4295146Z     return send_request.json()
2021-10-04T08:38:22.4296050Z   File "/home/zuser/.local/lib/python3.9/site-packages/requests/models.py", line 900, in json
2021-10-04T08:38:22.4308173Z     return complexjson.loads(self.text, **kwargs)
2021-10-04T08:38:22.4308805Z   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
2021-10-04T08:38:22.4316470Z     return _default_decoder.decode(s)
2021-10-04T08:38:22.4317065Z   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
2021-10-04T08:38:22.4325654Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2021-10-04T08:38:22.4326278Z   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
2021-10-04T08:38:22.4326950Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2021-10-04T08:38:22.4327638Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by anandtiwarics** [comment]
can you please post more information on what command are you using and setups to reproduce? as per error logs seems you are using archerysec-cli. can you try with this [sample report](https://raw.githubusercontent.com/archerysec/report-sample/main/Trivy/trivy_results.json).

**Comment by Premfer** [comment]
@anandtiwarics Thanks for the quick reply, yes I am using archerysec-cli with the below command

`archerysec-cli -h http://*****:8000 -**** -p /report/sample/trivy.json --file-type=JSON --target=ASFLKSF --scanner=trivy --project=eaf6f89e-56ee-4ef7-8257-07b7136c9e31 --upload`

The file you sent is uploaded successfully. The file generated by trivy is [report](url)

**Comment by Premfer** [comment]
@anandtiwarics Thanks for the quick reply, yes I am using archerysec-cli with the below command

`archerysec-cli -h http://*****:8000 -**** -p /report/sample/trivy.json --file-type=JSON --target=ASFLKSF --scanner=trivy --project=eaf6f89e-56ee-4ef7-8257-07b7136c9e31 --upload`

The file you sent is uploaded successfully. The file generated by trivy is  slightly has extra headers. The version of trivy is 0.19.2.
Can you please let know which version is supported

**Comment by anandtiwarics** [comment]
@Premfer I got it. Thanks for the report. I'll update our trivy parser for newer version support.

**Comment by anandtiwarics** [comment]
@Premfer pushed the initial fix. can you please verify from your end? below archerysec-cli command

``` archerysec-cli -h http://127.0.0.1:8000 -t c7etL_AsbsFNmfg6L5adu53nCxrYkvxcayIzu5cGCIjiGOz8HSxS8B9Ek1Mb6FCq -p /Downloads/results.json --file-type=JSON --target=ASFLKSF --scanner=trivy --project=cf9168e9-a8de-4036-b592-fc866ccea968 --upload ```

**Comment by anandtiwarics** [comment]
Seems you are trying to upload large file data. I would suggest uploading a smaller report or wait until it's finished.

**Comment by Premfer** [comment]
@anandtiwarics when the vulnerability list is high like around 25000 it takes around 2 hrs to upload. Is this expected? we are running this in the ci pipeline, so other jobs waits for long time, Is there something that can be done to increase the performance?
