### ISSUE TITLE
Cannot create user after fresh installation

### ISSUE THREAD

**Issue by usernameue** [archerysec/archerysec#514]
## EXPLANATION OF THE ISSUE

I've just installed archerysec on Windows virtual machine, followed the steps in install.md. When I execute manage.py initadmin I get errors

## STEPS TO REPRODUCE THE ISSUE

```
1. Fresh installation of archerysec on WinServer 2019 VM
2. Execute 
	python manage.py initadmin
3. Result: error
```

## CONSOLE OUTPUT

```
C:\Users\user\Downloads\archerysec-master>python manage.py initadmin
Traceback (most recent call last):
  File "C:\Users\user\Downloads\archerysec-master\manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\user\Downloads\archerysec-master\archerysecurity\management\commands\initadmin.py", line 25, in handle
    if User.objects.count() == 0:
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 187, in __get__
    raise AttributeError(
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'user_management.UserProfile'
```

**Expected behavior**
Admin account is created

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser Firefox
 - Version 93

**Comment by hinoobmaster** [comment]
installation with docker has same output:

```bash
 docker run -e NAME=user -e EMAIL=user@user.com -e PASSWORD=admin@123A  -it --rm -p  8000:8000 archerysec/archerysec:latest
```

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/archerysec/app/archerysecurity/management/commands/initadmin.py", line 25, in handle
    if User.objects.count() == 0:
  File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 191, in __get__
    cls._meta.swapped,
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'user_management.UserProfile'
Apply Fixtures
Installed 3 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
=================================================================
User Created
User Name : user
User Email: user@user.com
Role : Admin
Done !
Now running application
[2021-12-05 22:42:40 +0000] [21] [INFO] Starting gunicorn 20.1.0
[2021-12-05 22:42:40 +0000] [21] [INFO] Listening at: http://0.0.0.0:8000 (21)
[2021-12-05 22:42:40 +0000] [21] [INFO] Using worker: gthread
[2021-12-05 22:42:40 +0000] [24] [INFO] Booting worker with pid: 24
```

**Comment by anandtiwarics** [comment]
we currently not support windows.
