### ISSUE TITLE
Unable to parse json files

### ISSUE THREAD

**Issue by pranay-harness** [archerysec/archerysec#567]
**Describe the bug**
While trying to upload scans using archerysec-cli in json format, I'm getting the below error

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/archerysec-cli", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/archerysec_cli/cli/cli.py", line 468, in main
    scan_action()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/archerysec_cli/cli/cli.py", line 108, in scan_action
    upload_report(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/archerysec_cli/cli/cli.py", line 250, in upload_report
    scan_data = archerysec.json_upload(file=report_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/archerysec_cli/util/api.py", line 65, in json_upload
    return send_request.json()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**To Reproduce**
Ran the following command
archerysec-cli -h [http://********](http://%2A%2A%2A%2A%2A%2A%2A%2A/) -t ***** -p results.json --file-type=JSON --target=manager --scanner=trivy --project=****** --upload

Content for results.json was taken from here - https://raw.githubusercontent.com/archerysec/report-sample/main/Trivy/trivy_results.json

Tried on Mac, Ubuntu and a fresh Docker container running on ubuntu. All 3 had the same error

**Comment by esecure404** [comment]
I was getting same issue. did you find any solution?

**Comment by anandtiwarics** [comment]
please run the trivy latest version with all scan. sample report work: https://github.com/archerysec/report-sample/blob/main/Trivy/trivy-all.json
