### ISSUE TITLE
error http 500 on launching web scan ZAP

### ISSUE THREAD

**Issue by stasvolf** [archerysec/archerysec#57]
when launching ZAP scan view the "+Add Web Scan" button on new project wizard there is a 500 HTTP error :
Internal Server Error: /webscanners/scan_launch
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 115, in process_response
    if response.status_code == 404:
AttributeError: 'unicode' object has no attribute 'status_code'
[25/Jul/2018 19:51:04] "POST /webscanners/scan_launch HTTP/1.1" 500 15362
138965 [ZAP-ProxyThread-1] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/JSON/spider/action/excludeFromScan/] from [127.0.0.1]:
Missing Parameter (missing_parameter) : regex
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:423)
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
        at java.lang.Thread.run(Thread.java:748)
138976 [ZAP-ProxyThread-2] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/JSON/replacer/action/addRule/] from [127.0.0.1]:
Missing Parameter (missing_parameter) : replacement
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:423)
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
        at java.lang.Thread.run(Thread.java:748)
it is important to mention that the scan actually launches.
from my inspection the parameters passed to the server via POST are ok.

**Comment by anandtiwarics** [comment]
Are you using local or docker ?

**Comment by stasvolf** [comment]
locally(by the way - Awesome project!)

**Comment by anandtiwarics** [comment]
Thanks. What version of ZAP are you using? 

Make sure that the 2.7.0 version of zap installed also ZAP API should be enabled properly and accessible. 
I would recommend you to follow doc: https://docs.archerysec.info/Scanners/zap-scanner/

If you still getting issue let me know.

**Comment by stasvolf** [comment]
i am using 2.7.0 and the API is accessible and configured because i am able to launch and read reports of ZAP scans.
it looks like this error:
AttributeError: 'unicode' object has no attribute 'status_code'

caused by referencing to string and not the object of the response, any way when i will have time i will try to help and fix this issue.

**Comment by anandtiwarics** [comment]
can you please share error screenshot?

AttributeError: 'unicode' object has no attribute 'status_code' is not a problem, still the scan trigger to ZAP. 

![image](https://user-images.githubusercontent.com/4271325/43211418-14694b40-904f-11e8-9da9-5ef0b66fa285.png)

**Comment by anandtiwarics** [comment]
I hope the issue will be resolved now.
