### ISSUE TITLE
run.sh file giving errors after restarting archerysec

### ISSUE THREAD

**Issue by ihangnalli-cci** [archerysec/archerysec#576]
[2022-11-02 10:14:12 +0530] [11963] [INFO] Starting gunicorn 20.1.0
[2022-11-02 10:14:12 +0530] [11963] [INFO] Listening at: http://0.0.0.0:8000 (11963)
[2022-11-02 10:14:12 +0530] [11963] [INFO] Using worker: threads
[2022-11-02 10:14:12 +0530] [11968] [INFO] Booting worker with pid: 11968
[2022-11-02 10:14:12 +0530] [11968] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kali/Documents/archerysec/archerysecurity/wsgi.py", line 30, in <module>
    from whitenoise import WhiteNoise
ModuleNotFoundError: No module named 'whitenoise'
[2022-11-02 10:14:12 +0530] [11968] [INFO] Worker exiting (pid: 11968)
[2022-11-02 10:14:12 +0530] [11963] [INFO] Shutting down: Master
[2022-11-02 10:14:12 +0530] [11963] [INFO] Reason: Worker failed to boot.

**Comment by ihangnalli-cci** [comment]
resolved
