### ISSUE TITLE
Arachniscanner error

### ISSUE THREAD

**Issue by PekkaJalonen** [archerysec/archerysec#591]
**Describe the bug**
Error when launching arachni scanner. Issue is same as in #325 I tested removing same additional spaces as were in 325 and it works now in my test environment.

023-01-04T12:21:41.228935318Z Traceback (most recent call last):
2023-01-04T12:21:41.228942518Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
2023-01-04T12:21:41.228947718Z     response = get_response(request)
2023-01-04T12:21:41.228961718Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
2023-01-04T12:21:41.228968918Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-01-04T12:21:41.228973818Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2023-01-04T12:21:41.228978618Z     return view_func(*args, **kwargs)
2023-01-04T12:21:41.228983218Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
2023-01-04T12:21:41.228988018Z     return self.dispatch(request, *args, **kwargs)
2023-01-04T12:21:41.228992418Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
2023-01-04T12:21:41.228997018Z     response = self.handle_exception(exc)
2023-01-04T12:21:41.229001318Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
2023-01-04T12:21:41.229005918Z     self.raise_uncaught_exception(exc)
2023-01-04T12:21:41.229044619Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2023-01-04T12:21:41.229069219Z     raise exc
2023-01-04T12:21:41.229074719Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
2023-01-04T12:21:41.229102319Z     response = handler(request, *args, **kwargs)
2023-01-04T12:21:41.229107819Z   File "/home/archerysec/app/webscanners/arachniscanner/views.py", line 240, in post
2023-01-04T12:21:41.229130419Z     ProjectDb.objects.filter(uu_id=project_uu_id).values("id").get()["id"]
2023-01-04T12:21:41.229137119Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
2023-01-04T12:21:41.229142519Z     raise self.model.DoesNotExist(
2023-01-04T12:21:41.229147519Z projects.models.ProjectDb.DoesNotExist: ProjectDb matching query does not exist.
2023-01-04T12:21:41.237725883Z ERROR:django.request: Internal Server Error: /arachniscanner/arachni_scan_launch/ (2023-01-04 14:21:41; log.py:224)
2023-01-04T12:21:41.237749783Z Traceback (most recent call last):
2023-01-04T12:21:41.237757083Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
2023-01-04T12:21:41.237762283Z     response = get_response(request)
2023-01-04T12:21:41.237767083Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
2023-01-04T12:21:41.237783783Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-01-04T12:21:41.237790383Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2023-01-04T12:21:41.237911984Z     return view_func(*args, **kwargs)
2023-01-04T12:21:41.237925984Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
2023-01-04T12:21:41.237931584Z     return self.dispatch(request, *args, **kwargs)
2023-01-04T12:21:41.237936585Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
2023-01-04T12:21:41.237941785Z     response = self.handle_exception(exc)
2023-01-04T12:21:41.237946885Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
2023-01-04T12:21:41.237952085Z     self.raise_uncaught_exception(exc)
2023-01-04T12:21:41.237957085Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2023-01-04T12:21:41.237962385Z     raise exc
2023-01-04T12:21:41.237967385Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
2023-01-04T12:21:41.237972585Z     response = handler(request, *args, **kwargs)
2023-01-04T12:21:41.237977585Z   File "/home/archerysec/app/webscanners/arachniscanner/views.py", line 240, in post
2023-01-04T12:21:41.237982885Z     ProjectDb.objects.filter(uu_id=project_uu_id).values("id").get()["id"]
2023-01-04T12:21:41.237988185Z   File "/home/archerysec/app/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
2023-01-04T12:21:41.237993485Z     raise self.model.DoesNotExist(
2023-01-04T12:21:41.237998485Z projects.models.ProjectDb.DoesNotExist: ProjectDb matching query does not exist.

**To Reproduce**
1. Start dynamic scan with some project and target and using arachni as scanner

**Expected behavior**
Should start as expected

**Comment by anandtiwarics** [comment]
fixed the issue. @PekkaJalonen thanks for raising this issue.
