### ISSUE TITLE
internal server error while running in local

### ISSUE THREAD

**Issue by Dhinendran** [archerysec/archerysec#82]
Internal Server Error: /zapscanner/zap_scan/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dhinendran/Downloads/archerysec/webscanners/zapscanner/views.py", line 120, in zap_scan
    if scans_status == '100':
NameError: global name 'scans_status' is not defined
Expecting value: line 1 column 1 (char 0)
[01/Oct/2018 09:45:30] "POST /zapscanner/zap_scan/ HTTP/1.1" 500 16068

**Comment by anandtiwarics** [comment]
Can you provide us with more error logs? Seems that zap API endpoint has not been configured properly. please follow archerysec doc https://docs.archerysec.info/Scanners/zap-scanner/
